# Generated by Django 5.1.2 on 2024-10-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('client', models.CharField(blank=True, max_length=250, null=True)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(blank=True, default=True, null=True)),
                ('is_substracted_from_stock', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'ordering': ('-sold_at',),
            },
        ),
    ]
